name: Lab Exam CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2 Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3 Install dependencies
      - name: Install dependencies
        run: npm install

      # 4 Build project
      - name: Build project
        run: npm run build

      # 5 Deploy to GitHub Pages
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d dist -u "github-actions-bot <support@github.com>" -r https://x-access-token:${GITHUB_TOKEN}@github.com/SAI30570SREERachapudi/LabExam-CICD.git
